# 2 Spicy
2spicy:
  launcher_path: "elf"

# After Burner Climax (SDX)
abclisdx:
  launcher_path: ""

# Ghost Squad Evolution
ghostsev:
  launcher_path: "vsg_l"

# Harley Davidson King of the Road
hdkotr:
  launcher_path: "elf"

# The House of the Dead 4 (Rev A)
hotd4a:
  launcher_path: "elf"
        
# The House of the Dead 4 - Special
hotd4sp:
  launcher_path: "elf"

# The House of the Dead EX
hotdex:
  launcher_path: "elf"

# Hummer
hummer:
  launcher_path: ""

# Hummer Extreme Edition
hummerxt:
  launcher_path: ""

# Initial D Arcade Stage 4 (Rev B)
initiad4b:
  launcher_path: ""

# Initial D 4 (Export) (Rev D)
initiad4ex:
  launcher_path: ""

# Initial D 5 (Export) (2.0)
initiad5exa:
  launcher_path: ""

# Let's Go Jungle
letsgoju:
  launcher_path: ""

# Let's Go Jungle - Special
letsgojusp:
  launcher_path: ""

# Outrun 2 SP SDX (Rev A)
outr2sdx:
  display_name: "Outrun 2 SP SDX (Rev A)"
  launcher_path: "Jennifer"

# Outrun 2 SP SDX (Bootleg)
outr2sdxg:
  display_name: "Outrun 2 SP SDX (Bootleg)"
  launcher_path: "Jennifer"

# Primeval Hunt
primevah:
  display_name: "Primeval Hunt"
  launcher_path: "prog"

# R-Tuned: Ultimate Street Racing
rtuned:
  display_name: "R-Tuned: Ultimate Street Racing"
  launcher_path: ""

# Rambo (Export)
rambo:
  display_name: "Rambo (Export)"
  launcher_path: "elf"

# Sega Race-TV (Export)
segartv:
  display_name: "Sega Race-TV (Export)"
  launcher_path: ""

# Virtua Fighter 5
vf5:
  display_name: "Virtua Fighter 5"
  launcher_path: ""

# Virtua Fighter 5 (Rev E)(ver C)
vf5e:
  display_name: "Virtua Fighter 5 (Rev E)(ver C)"
  launcher_path: ""

# Virtua Fighter 5 Final Showdown (Rev A, v2.0)
vf5fsa2:
  display_name: "Virtua Fighter 5 Final Showdown (Rev A, v2.0)"
  launcher_path: ""

# Virtua Fighter 5 R (Rev G)
vf5r:
  display_name: "Virtua Fighter 5 R (Rev G)"
  launcher_path: ""

# Virtua Tennis 3 (Rev C)
vtennis3:
  display_name: "Virtua Tennis 3 (Rev C)"
  launcher_path: "vt3_Lindbergh"
